name: rebus open textbooks
favicon: null
layout_spectrum: 0.1952
typography_spectrum: 0.73649
title: Rebus Open Textbooks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.375
  lightness: 0.8043011974077672
  saturation: 0.875
  rhythmicContrast: 0.016296675894409418
purpose: []
