name: rebus open textbooks
favicon: null
layout_spectrum: 0.61846
typography_spectrum: 0.70862
title: Rebus Open Textbooks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#2d2d2f'
    - '#b2b9c9'
    - '#647295'
    - '#689bec'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
